# Generated by Django 4.2 on 2023-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_cartitem_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='cartOrder',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
