# Generated by Django 4.2 on 2023-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_cartorder_cartorder_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
