# Generated by Django 4.2 on 2023-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oeder_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
