# Generated by Django 4.2 on 2023-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_order_oeder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
