# Generated by Django 4.2 on 2023-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oeder_name',
            new_name='order_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
